Conference.create!(name: 'American Athletic Conference', yrFounded: 1979, totalMembers: 11, headquarters: 'Providence, RI')
Conference.create!(name: 'Atlantic Coast Conference', yrFounded: 1953, totalMembers: 15, headquarters: 'Greensboro, NC')
Conference.create!(name: 'Big Ten Conference', yrFounded: 1896, totalMembers: 14, headquarters: 'Rosemont, IL')
Conference.create!(name: 'Big 12 Conference', yrFounded: 1996, totalMembers: 10, headquarters: 'Irving, TX')
Conference.create!(name: 'Conference USA', yrFounded: 1995, totalMembers: 14, headquarters: 'Irving, TX')
Conference.create!(name: 'Division I FBS Independents', yrFounded: 0, totalMembers: 3, headquarters: 'None')
Conference.create!(name: 'Mid-American Conference', yrFounded: 1946, totalMembers: 12, headquarters: 'Cleveland, OH')
Conference.create!(name: 'Mountain West Conference', yrFounded: 1999, totalMembers: 11, headquarters: 'Colorado Springs, CO')
Conference.create!(name: 'Pac-12 Conference', yrFounded: 1959, totalMembers: 12, headquarters: 'Walnut Creek, CA')
Conference.create!(name: 'Southeastern Conference', yrFounded: 1932, totalMembers: 14, headquarters: 'Birmingham, AL')
Conference.create!(name: 'Sun Belt Conference', yrFounded: 1976, totalMembers: 11, headquarters: 'New Orleans, LA')